### ISSUE TITLE
"rake secret" fails

### ISSUE THREAD

**Issue by polnetwork** [Platoniq/decidim-install#22]
"rake secret" fails on my setup.
~/decidim-app# rake secret
rake aborted!
LoadError: cannot load such file -- bundler/setup
/root/decidim-app/config/boot.rb:3:in `<top (required)>'
/root/decidim-app/config/application.rb:1:in `require_relative'
/root/decidim-app/config/application.rb:1:in `<top (required)>'
/root/decidim-app/Rakefile:4:in `require_relative'
/root/decidim-app/Rakefile:4:in `<top (required)>'
(See full trace by running task with --trace)

Can be related with an error on a previous step on te "bundle install"?

~/decidim-app# bundle install
Traceback (most recent call last):
	2: from /root/.rbenv/versions/2.5.1/bin/bundle:23:in `<main>'
	1: from /root/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
/root/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundle (Gem::GemNotFoundException)

Thank's for all!

**Comment by microstudi** [comment]
Probably, let's fix #19 first
