### ISSUE TITLE
Can't continue install on "decidim decidim-app" step

### ISSUE THREAD

**Issue by polnetwork** [Platoniq/decidim-install#23]
Hi, I'm on a clean Ubuntu 18.04 server installation.
I'v gone until step "decidim decidim-app" without errors after changing the sources.list from here https://stackoverflow.com/questions/51778272/unable-to-install-phusion-passenger-on-ubuntu-server-18-04
Maybe there's a problem with the bundler?
Thank's for all!
------------
Here's the output of my console:

decidim decidim-app
      create
      create  README.md
      create  Rakefile
      create  .ruby-version
      create  config.ru
      create  .gitignore
      create  Gemfile
         run  git init from "."
Initialized empty Git repository in /home/decidim/decidim-app/.git/
      create  package.json
      create  app
      create  app/assets/config/manifest.js
      create  app/assets/javascripts/application.js
      create  app/assets/javascripts/cable.js
      create  app/assets/stylesheets/application.css
      create  app/channels/application_cable/channel.rb
      create  app/channels/application_cable/connection.rb
      create  app/controllers/application_controller.rb
      create  app/helpers/application_helper.rb
      create  app/jobs/application_job.rb
      create  app/mailers/application_mailer.rb
      create  app/models/application_record.rb
      create  app/views/layouts/application.html.erb
      create  app/views/layouts/mailer.html.erb
      create  app/views/layouts/mailer.text.erb
      create  app/assets/images/.keep
      create  app/assets/javascripts/channels
      create  app/assets/javascripts/channels/.keep
      create  app/controllers/concerns/.keep
      create  app/models/concerns/.keep
      create  bin
      create  bin/bundle
      create  bin/rails
      create  bin/rake
      create  bin/setup
      create  bin/update
      create  bin/yarn
      create  config
      create  config/routes.rb
      create  config/application.rb
      create  config/environment.rb
      create  config/cable.yml
      create  config/puma.rb
      create  config/spring.rb
      create  config/storage.yml
      create  config/environments
      create  config/environments/development.rb
      create  config/environments/production.rb
      create  config/environments/test.rb
      create  config/initializers
      create  config/initializers/application_controller_renderer.rb
      create  config/initializers/assets.rb
      create  config/initializers/backtrace_silencers.rb
      create  config/initializers/content_security_policy.rb
      create  config/initializers/cookies_serializer.rb
      create  config/initializers/cors.rb
      create  config/initializers/filter_parameter_logging.rb
      create  config/initializers/inflections.rb
      create  config/initializers/mime_types.rb
      create  config/initializers/new_framework_defaults_5_2.rb
      create  config/initializers/wrap_parameters.rb
      create  config/locales
      create  config/locales/en.yml
      create  config/master.key
      append  .gitignore
      create  config/boot.rb
      create  config/database.yml
      create  db
      create  db/seeds.rb
      create  lib
      create  lib/tasks
      create  lib/tasks/.keep
      create  lib/assets
      create  lib/assets/.keep
      create  log
      create  log/.keep
      create  public
      create  public/404.html
      create  public/422.html
      create  public/500.html
      create  public/apple-touch-icon-precomposed.png
      create  public/apple-touch-icon.png
      create  public/favicon.ico
      create  public/robots.txt
      create  tmp
      create  tmp/.keep
      create  tmp/cache
      create  tmp/cache/assets
      create  vendor
      create  vendor/.keep
      create  test/fixtures
      create  test/fixtures/.keep
      create  test/fixtures/files
      create  test/fixtures/files/.keep
      create  test/controllers
      create  test/controllers/.keep
      create  test/mailers
      create  test/mailers/.keep
      create  test/models
      create  test/models/.keep
      create  test/helpers
      create  test/helpers/.keep
      create  test/integration
      create  test/integration/.keep
      create  test/test_helper.rb
      create  test/system
      create  test/system/.keep
      create  test/application_system_test_case.rb
      create  storage
      create  storage/.keep
      create  tmp/storage
      create  tmp/storage/.keep
      remove  config/initializers/cors.rb
      remove  config/initializers/new_framework_defaults_5_2.rb
       force  config/database.yml
      create  app/controllers/decidim_controller.rb
      create  Dockerfile
      create  docker-compose.yml
      create  docker-compose-etherpad.yml
       force  config/cable.yml
       force  README.md
      create  LICENSE-AGPLv3.txt
       force  Gemfile
      create  Gemfile.lock
        gsub  Gemfile
        gsub  Gemfile
        gsub  Gemfile
        gsub  Gemfile
        gsub  Gemfile
         run  bundle install from "."
Traceback (most recent call last):
	2: from /home/decidim/.rbenv/versions/2.5.1/bin/bundle:23:in `<main>'
	1: from /home/decidim/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
/home/decidim/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundle (Gem::GemNotFoundException)
        gsub  config/boot.rb
      append  .gitignore
      remove  public/404.html
      remove  public/500.html
      create  config/initializers/decidim.rb
       route  mount Decidim::Core::Engine => '/'
      append  db/seeds.rb
      create  config/initializers/carrierwave.rb
      create  config/initializers/social_share_button.rb
      create  config/secrets.yml
      remove  app/views/layouts/application.html.erb
      remove  app/views/layouts/mailer.text.erb
      append  app/assets/javascripts/application.js
        gsub  app/assets/javascripts/application.js
      insert  app/assets/stylesheets/application.css
      create  app/assets/stylesheets/decidim.scss
      insert  config/environments/development.rb
      insert  config/environments/test.rb
        gsub  config/environments/production.rb
      insert  config/environments/production.rb
Traceback (most recent call last):
	4: from bin/rails:3:in `<main>'
	3: from bin/rails:3:in `require_relative'
	2: from /home/decidim/decidim-app/config/boot.rb:3:in `<top (required)>'
	1: from /home/decidim/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/home/decidim/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- bundler/setup (LoadError)

**Comment by microstudi** [comment]
There's definitively something with the bundler or another more obscure involved gem. Another user pointed the same thing.
I will have to repeat the process and use 0.16 instead of 0.14.

As this is related to #19 I will continue the conversation there
