### ISSUE TITLE
confirmation mail not sent

### ISSUE THREAD

**Issue by jocarcelen** [Platoniq/decidim-install#36]
I follow instructions to configure a Gmail account (https://github.com/Platoniq/decidim-install/blob/master/basic-config.md), I tried options 1 and 2, but when I create an organization I do not receive any confirmation message. The log shows an EOF error:

> I, [2019-08-12T13:35:45.233270 #14381]  INFO -- : [63841e6d-900c-4965-90ab-513494ce5c46] Completed 200 OK in 26ms (Views: 23.2ms | ActiveRecord: 1.9ms)
I, [2019-08-12T13:35:45.300813 #14381]  INFO -- : [ActiveJob] [ActionMailer::DeliveryJob] [6b426a11-fe5a-4dfe-91bc-c3d0b60a04d9] Sent mail to xxx@xxx (99.2ms)
D, [2019-08-12T13:35:45.300868 #14381] DEBUG -- : [ActiveJob] [ActionMailer::DeliveryJob] [6b426a11-fe5a-4dfe-91bc-c3d0b60a04d9] Date: Mon, 12 Aug 2019 13:35:45 +0200
From: xxx@gmail.com
To: xxx@xxx
Message-ID: <5d514f11315ea_382d2b2629802a80784ef@decidim.mail>
Subject: =?UTF-8?Q?Instruccions_de_confirmaci=C3=B3?=
Mime-Version: 1.0
>
>...........
> 
> ----==_mimepart_5d514f1131330_382d2b2629802a807838b--
> 
> E, [2019-08-12T13:35:45.301014 #14381] ERROR -- : [ActiveJob] [ActionMailer::DeliveryJob] [6b426a11-fe5a-4dfe-91bc-c3d0b60a04d9] Error performing ActionMailer::DeliveryJob (Job ID: 6b426a11-fe5a-4dfe-91bc-c3d0b60a04d9) from Async(mailers) in 290.43ms: EOFError (end of file reached):
> /home/ajpolinya/.rbenv/versions/2.6.3/lib/ruby/2.6.0/net/protocol.rb:225:in `rbuf_fill'
> /home/ajpolinya/.rbenv/versions/2.6.3/lib/ruby/2.6.0/net/protocol.rb:191:in `readuntil'
> /home/ajpolinya/.rbenv/versions/2.6.3/lib/ruby/2.6.0/net/protocol.rb:201:in `readline'
> /home/ajpolinya/.rbenv/versions/2.6.3/lib/ruby/2.6.0/net/smtp.rb:950:in `recv_response'
> /home/ajpolinya/.rbenv/versions/2.6.3/lib/ruby/2.6.0/net/smtp.rb:935:in `block in getok'
> /home/ajpolinya/.rbenv/versions/2.6.3/lib/ruby/2.6.0/net/smtp.rb:960:in `critical'
> /home/ajpolinya/.rbenv/versions/2.6.3/lib/ruby/2.6.0/net/smtp.rb:933:in `getok'
> /home/ajpolinya/.rbenv/versions/2.6.3/lib/ruby/2.6.0/net/smtp.rb:826:in `helo'
> /home/ajpolinya/.rbenv/versions/2.6.3/lib/ruby/2.6.0/net/smtp.rb:600:in `do_helo'
> /home/ajpolinya/.rbenv/versions/2.6.3/lib/ruby/2.6.0/net/smtp.rb:554:in `do_start'
> /home/ajpolinya/.rbenv/versions/2.6.3/lib/ruby/2.6.0/net/smtp.rb:518:in `start'

Any idea what's happening?
Thanks

**Comment by microstudi** [comment]
well it seems that rails is trying to send the mail but it fails. My first idea would be to ensure that you can use your SMTP settings to send email. You can check that independently from rails/decidim. Try something like https://www.smtper.net/

If you can send emails successfully, then maybe you have some misconfiguration. Hard to know without viewing your code
