### ISSUE TITLE
SMTP error

### ISSUE THREAD

**Issue by Hapari** [Platoniq/decidim-install#47]
I got this error message from "grep ERROR ~/decidim-app/log/production.log -A3 -B3". I have checked many times that I have followed all instructions and also checked gmail connection with smtper.net. Any ideas?

E, [2020-03-17T22:49:33.950574 #31662] ERROR -- : [ActiveJob] [ActionMailer::DeliveryJob] [d38f1b9c-5f22-470b-b6a7-f3d1eb1db000] Error performing ActionMailer::DeliveryJob (Job ID: d38f1b9c-5f22-470b-b6a7-f3d1eb1db000) from Async(mailers) in 982.51ms: Net::SMTPAuthenticationError (535-5.7.8 Username and Password not accepted. Learn more at
):
/home/decidim/.rbenv/versions/2.6.3/lib/ruby/2.6.0/net/smtp.rb:981:in `check_auth_response'
/home/decidim/.rbenv/versions/2.6.3/lib/ruby/2.6.0/net/smtp.rb:736:in `auth_plain'

**Comment by Hapari** [comment]
I tryed test with "bin/rails console -e production" command and got this:

Traceback (most recent call last):
SyntaxError ((irb):4: syntax error, unexpected tIVAR, expecting ')')
...from: ’***@gmail.com’, to: ’***@***.*…
...                         ^~~~~~
(irb):4: syntax error, unexpected tLABEL, expecting '='
…***@gmail.com’, to: ’***@***.***’, sub...
...                            ^~~
(irb):4: syntax error, unexpected ')', expecting end-of-input
...ody: "Hello, you've got mail!").deliver
...

**Comment by javims90** [comment]
Hi @Hapari , 
Have you been able to solve your problem?

**Comment by microstudi** [comment]
There some syntax error, can you show your configuration?
