### ISSUE TITLE
SMTP authentication error (doh?)

### ISSUE THREAD

**Issue by Rggb** [Platoniq/decidim-install#59]
I'm trying to configure a local Postfix installation to delivery mails.

All things work fine with an external service (eg. Google). After setting up the parameters needed by postfix for a particular organization:

![image](https://user-images.githubusercontent.com/68006654/86908621-1e00d100-c117-11ea-8e51-a6428309375d.png)

mail delivery fails due to Net::SMTPAuthenticationError (in this example, using a newsletter):

> E, [2020-07-07T17:21:43.722460 #15284] ERROR -- : [ActiveJob] [Decidim::Admin::NewsletterDeliveryJob] [4fc8365c-26bb-4745-9a76-558349a53097] Error performing Decidim::Admin::NewsletterDeliveryJob (Job ID: 4fc8365c-26bb-4745-9a76-558349a53097) from Async(newsletter) in 2058.78ms: Net::SMTPAuthenticationError (503 5.5.1 Error: authentication not enabled
> ):
> /var/www/.rbenv/versions/2.6.3/lib/ruby/2.6.0/net/smtp.rb:981:in `check_auth_response'
> /var/www/.rbenv/versions/2.6.3/lib/ruby/2.6.0/net/smtp.rb:736:in `auth_plain'
> /var/www/.rbenv/versions/2.6.3/lib/ruby/2.6.0/net/smtp.rb:728:in `authenticate'
> /var/www/.rbenv/versions/2.6.3/lib/ruby/2.6.0/net/smtp.rb:565:in `do_start'
> /var/www/.rbenv/versions/2.6.3/lib/ruby/2.6.0/net/smtp.rb:518:in `start'

Of course I don't need authentication using local Postfix server, while I (others) need it.

I tried to play with config, without success. Suggestions?

**Comment by microstudi** [comment]
If you are using postfix, simply use `sendmail` as delivery method and comment everything else. This values won't be used (leave them empty)

In `config/environments/production.rb`:

![imatge](https://user-images.githubusercontent.com/1401520/88162545-c3d13700-cc11-11ea-9f04-99ebd747030d.png)

**Comment by Rggb** [comment]
Thanks for your reply.

This will affect the entire environment afaik. so every organization will use sendmail method (in my config, the local Postfix), that's not what I'm trying to do.

By now I configured authentication for Postfix. I need an hack, will play with the code again in the future when worktime < lifetime ;)

Thanks again
