### ISSUE TITLE
Can't send Mail

### ISSUE THREAD

**Issue by jack8387** [Platoniq/decidim-install#64]
Hi,
I install DECIDIM and i can't send mail

In gmail i enable “less secure applications”.

My config is : 
Application.yml
  SMTP_USERNAME: my user
  SMTP_PASSWORD: my pwd
  SMTP_ADDRESS: smtp.gmail.com
  SMTP_DOMAIN: gmail.com

secrets.yml
 production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  smtp_username: <%= ENV["SMTP_USERNAME"] %>
  smtp_password: <%= ENV["SMTP_PASSWORD"] %>
  smtp_address: <%= ENV["SMTP_ADDRESS"] %>
  smtp_domain: <%= ENV["SMTP_DOMAIN"] %>
  smtp_port: "587"
  smtp_starttls_auto: true
  smtp_authentication: "plain"

environnements/production.rb
 config.action_mailer.smtp_settings = {
    :address        => Rails.application.secrets.smtp_address,
    :port           => Rails.application.secrets.smtp_port,
    :authentication => Rails.application.secrets.smtp_authentication,
    :user_name      => Rails.application.secrets.smtp_username,
    :password       => Rails.application.secrets.smtp_password,
    :domain         => Rails.application.secrets.smtp_domain,
    :enable_starttls_auto => Rails.application.secrets.smtp_starttls_auto,
    :openssl_verify_mode => 'none',
    :ssl =>                   true,
    :tls =>                  true
  }

I don't understand why ?

Thanks for help

**Comment by microstudi** [comment]
do you have a log with the error message?
check if your username is the full mail also

**Comment by jack8387** [comment]
When i do : grep ERRR log/production.log -A3 -B3
i have nothing
and 
I have on log/production.log this message
[2020-10-19T19:55:50.463062 #3229] DEBUG -- :   Delayed::Backend::ActiveRecord::Job Load (1.1ms)  UPDATE "delayed_jobs" SET locked_at = '2020-10-19 17:55:50.461125', locked_by = 'delayed_job host:decidim-signes pid:3229' WHERE id IN (SELECT  "delayed_jobs"."id" FROM "delayed_jobs" WHERE ((run_at <= '2020-10-19 17:55:50.460385' AND (locked_at IS NULL OR locked_at < '2020-10-19 13:55:50.460425') OR locked_by = 'delayed_job host:decidim-signes pid:3229') AND failed_at IS NULL) ORDER BY priority ASC, run_at ASC LIMIT 1 FOR UPDATE) RETURNING *
D, [2020-10-19T19:55:55.471963 #3229] DEBUG -- :   Delayed::Backend::ActiveRecord::Job Load (1.1ms)  UPDATE "delayed_jobs" SET locked_at = '2020-10-19 17:55:55.470279', locked_by = 'delayed_job host:decidim-signes pid:3229' WHERE id IN (SELECT  "delayed_jobs"."id" FROM "delayed_jobs" WHERE ((run_at <= '2020-10-19 17:55:55.469567' AND (locked_at IS NULL OR locked_at < '2020-10-19 13:55:55.469592') OR locked_by = 'delayed_job host:decidim-signes pid:3229') AND failed_at IS NULL) ORDER BY priority ASC, run_at ASC LIMIT 1 FOR UPDATE) RETURNING *

**Comment by microstudi** [comment]
can you try
`grep ERROR log/production.log -A3 -B3`

**Comment by jack8387** [comment]
grep ERROR log/production.log -A3 -B3
send me  nothing

**Comment by microstudi** [comment]
Try to configure evironments/production.rb as:
```ruby
  config.action_mailer.smtp_settings = {
    :address        => Rails.application.secrets.smtp_address,
    :port           => Rails.application.secrets.smtp_port,
    :authentication => Rails.application.secrets.smtp_authentication,
    :user_name      => Rails.application.secrets.smtp_username,
    :password       => Rails.application.secrets.smtp_password,
    :domain         => Rails.application.secrets.smtp_domain,
    :enable_starttls_auto => Rails.application.secrets.smtp_starttls_auto,
    :openssl_verify_mode => 'none'
  }

```

**Comment by jack8387** [comment]
My production.rb
 config.action_mailer.smtp_settings = {
    :address        => Rails.application.secrets.smtp_address,
    :port           => Rails.application.secrets.smtp_port,
    :authentication => Rails.application.secrets.smtp_authentication,
    :user_name      => Rails.application.secrets.smtp_username,
    :password       => Rails.application.secrets.smtp_password,
    :domain         => Rails.application.secrets.smtp_domain,
    :enable_starttls_auto => Rails.application.secrets.smtp_starttls_auto,
    :openssl_verify_mode => 'none',
    :ssl =>                   true,
    :tls =>                  true
  }

**Comment by jack8387** [comment]
Hi, 
when i send a mail from : 
 bin/rails console -e production
 mailer.mail(from ............).deliver

is ok, i receive the mail.

But when i create a admin, no mail send, and my admin can't use dashboard

Whith decidim, i saw only one error :
 [2020-10-24T17:52:26.562499 #77538] ERROR -- : [ActiveJob] [ActionMailer::DeliveryJob] [13a0f5a8-c925-4be4-bfc3-da04f2f533d7] Error performing ActionMailer::DeliveryJob (Job ID: 13a0f5a8-c925-4be4-bfc3-da04f2f533d7) from Async(mailers) in 2346.94ms: Net::SMTPSyntaxError (501 Syntax: HELO hostname.
/home/jacquesa/.rbenv/versions/2.6.3/lib/ruby/2.6.0/net/smtp.rb:969:in `check_response'
/home/jacquesa/.rbenv/versions/2.6.3/lib/ruby/2.6.0/net/smtp.rb:937:in `getok

Have any ideas

Thanks

**Comment by microstudi** [comment]
is it possible that you need to restart delayedjob after making the updates in your config?

**Comment by jack8387** [comment]
I restart the delayedjob and i have the same problem

**Comment by microstudi** [comment]
Sorry, I'm not sure how can I help you, it really seems some misconfiguration (reading the error message)

**Comment by mauriziomarini** [comment]
When you use console
bin/rails console -e production
the system use configuration:
->   config/application.yml
->   config/secrets.yml
->   config/environments/production.rb

when you click
_**Didn't receive confirmation instructions?**_

the system use the organization configuration
I just entered 587 and the with mouse wheel down to page to click save
but mouse wheel subtract something to 587 **### _damn!!!_**

take care of it!
