### ISSUE TITLE
Can't send email (gmail)

### ISSUE THREAD

**Issue by AnthonyFon** [Platoniq/decidim-install#68]
Hi,

Sorry, I have another problem, but I really not understand the log message.
We can't send may with our Decidim. I did all the thing which are in the guide.

Maybe the log will speak to you :

----==_mimepart_5fd38c6e93ae3_529f2ac6bac620f45639--

E, [2020-12-11T16:12:46.675069 #21151] ERROR -- : [ActiveJob] [ActionMailer::DeliveryJob] [1031097e-4a06-44f4-878b-1c00a56e8c23] Error performing ActionMailer::DeliveryJob (Job ID: 1031097e-4a06-44f4-878b-1c00a56e8c23) from Async(mailers) in 353.57ms: EOFError (end of file reached):
/home/decidim/.rbenv/versions/2.6.3/lib/ruby/2.6.0/net/protocol.rb:225:in `rbuf_fill'
/home/decidim/.rbenv/versions/2.6.3/lib/ruby/2.6.0/net/protocol.rb:191:in `readuntil'
/home/decidim/.rbenv/versions/2.6.3/lib/ruby/2.6.0/net/protocol.rb:201:in `readline'

**Comment by BigSnicker** [comment]
If I recall correctly, set "force SSL" in /initializers/decidim.rb to false
and this should go away.

**Comment by AnthonyFon** [comment]
@BigSnicker, thank's, I will try.
Nothing to restart after this modification ?

**Comment by BigSnicker** [comment]
I would restart everything, just to be safe.

**Comment by AnthonyFon** [comment]
Reboot the server ? Or a command to run to restart everything ?

**Comment by BigSnicker** [comment]
I just reboot the server in that case. Probably overkill, but I'm working
on a test platform.

**Comment by AnthonyFon** [comment]
Hi,
I reinstall Decidim on a fresh install with the script.
I'm block with email, impossible to send. I put "force SSL" to false, the reboot, but I have always the same message : 
----==_mimepart_5fd4deec4113a_24a3fadbc9a6358359d4--

E, [2020-12-12T16:17:00.338084 #586] ERROR -- : [ActiveJob] [ActionMailer::DeliveryJob] [9a9da61e-d23a-417a-a8a0-ea6937cd36a2] Error performing ActionMailer::DeliveryJob (Job ID: 9a9da61e-d23a-417a-a8a0-ea6937cd36a2) from Async(mailers) in 699.42ms: EOFError (end of file reached):
/home/decidim/.rbenv/versions/2.6.6/lib/ruby/2.6.0/net/protocol.rb:225:in `rbuf_fill'
/home/decidim/.rbenv/versions/2.6.6/lib/ruby/2.6.0/net/protocol.rb:191:in `readuntil'
/home/decidim/.rbenv/versions/2.6.6/lib/ruby/2.6.0/net/protocol.rb:201:in `readline'

Another solution to solve this ?
Thanks a lot !

**Comment by BigSnicker** [comment]
Have you tested your SMTP credentials?

https://www.smtper.net/

**Comment by AnthonyFon** [comment]
Hi,
Thanks @BigSnicker. I have test my gmail account with smtper.net and I find a problem (not woking). I have use the option 2 of the guide (2 factor authentification and make a bypass for apllication) and that's working.
I reinstall all the plateform without script, because now, I don't have dashboard. So I make another fresh install.
Thanks for your help !
